[package]
name = "process-dispatcher"
version = "0.1.0"
edition = "2021"
default-run = "cli"

[dependencies]
bincode = "1.3.3"
byteorder = "1.5.0"
interprocess = "2.2.1"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.63"
